# Sample workflow for building and deploying a Hugo site to a subdirectory of another repository
name: Deploy Hugo resume site

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.111.3

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded

      - name: Checkout resume
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          path: resume

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        with:
          repo-token: ${{ secrets.PAT }}

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
        working-directory: ./resume

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/resume"
        working-directory: ./resume

      - name: Checkout main website
        uses: actions/checkout@v3
        with:
          repository: efahssi/elias-web
          token: ${{ secrets.PAT }}
          path: elias-web

      - name: Copy resume to main website
        run: |
          mkdir -p elias-web/public/resume
          cp -r resume/public/* elias-web/public/resume/

      - name: Commit and push changes
        run: |
          cd elias-web
          git config user.name "elias"
          git config user.email "elias@fahssi.ca"
          git add .
          git commit -m "Update resume" || exit 0  # Don't fail if no changes
          git push